// Vuex Mutations
export const MUTATE_USER = 'MUTATE_USER';
export const MUTATE_ADMIN = 'MUTATE_ADMIN';
export const MUTATE_TOKEN = 'MUTATE_TOKEN';
export const MUTATE_TENANT = 'MUTATE_TENANT';
export const MUTATE_RIGHT_DRAWER = 'MUTATE_RIGHT_DRAWER';
export const MUTATE_HOUSEHOLD_PAGINATION = 'MUTATE_HOUSEHOLD_PAGINATION';
export const MUTATE_HOUSEHOLD = 'MUTATE_HOUSEHOLD';
export const MUTATE_STUDENT_PAGINATION = 'MUTATE_STUDENT_PAGINATION';
export const MUTATE_STUDENT = 'MUTATE_STUDENT';

// Vuex Actions
export const SHOW_RIGHT_DRAWER = 'SHOW_RIGHT_DRAWER';
export const HIDE_RIGHT_DRAWER = 'HIDE_RIGHT_DRAWER';
export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGOUT_ACTION = 'LOGOUT_ACTION';
export const GET_LOGGED_ADMIN_ACTION = 'GET_ADMIN_FROM_TOKEN_ACTION';
export const GET_TENANT_ACTION = 'GET_TENANT_ACTION';
export const UPDATE_ME_ACTION = 'UPDATE_ME_ACTION';
export const PAGINATE_STUDENTS_ACTION = 'PAGINATE_STUDENTS_ACTION';
export const GET_STUDENT_DETAILS_ACTION = 'GET_STUDENT_DETAILS_ACTION';
export const PAGINATE_HOUSEHOLDS_ACTION = 'PAGINATE_HOUSEHOLDS_ACTION';
export const GET_HOUSEHOLD_DETAILS_ACTION = 'GET_HOUSEHOLD_DETAILS_ACTION';


// Other
export const TOKEN_COOKIE = 'token';
export const TENANT_HEADER = 'Alunos-Tenant';
